version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"  # Accès via http://localhost:8080
    volumes:
      - .:/var/www/html  # Tes fichiers PHP doivent être à la racine du projet
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: patients_db
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"  # Accès à phpMyAdmin via http://localhost:8081
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - appnet

volumes:
  dbdata:

networks:
  appnet:
